spring:
  application:
    name: eureka-server1
server:
  port: 8881
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
